---
title: "Justificativas - Legislatura Atual"
output:
  html_document:
    theme: paper
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  # message = FALSE,
  # warning = FALSE,
  # fig.cap = '',
  # fig.align = 'center',
  fig.width = 6,
  fig.height = 5
)
Sys.setenv(LANGUAGE="pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
options(scipen = 999)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(reactable)
library(ggchicklet)
library(ggbeeswarm)
library(hrbrthemes)
library(here)
theme_set(theme_ipsum_rc())
```

```{r}
justificativas = read_csv(here::here("data/ready/justificativas_19-21.csv"),
                          col_types = c("cciTiccccTcccll"))
```

Na análise, `texto_inicial` representa todo o texto que antecede a parte de justiticação no arquivo do Inteiro Teor da proposição. 

### Totais

```{r}
totais = justificativas %>% 
    summarise(palavras_texto = str_count(texto_inicial, '\\w+'),
              caracteres_texto = str_length(texto_inicial),
              palavras_justificativas = str_count(justificativa, '\\w+'),
              caracteres_justificativas = str_length(justificativa))
```

```{r}
totais %>% 
    summarise(`Palavras no texto inicial (milhões)` = round(sum(palavras_texto, na.rm = T) / 1e6, 1),
              `Mediana do texto inicial` = median(palavras_texto, na.rm = T),
              `Palavras nas justificativas (milhões)` = round(sum(palavras_justificativas, na.rm = T) / 1e6, 1),
              `Mediana das justificativas` = median(palavras_justificativas, na.rm = T),
              `Tamanho do texto (mediana)` = median(caracteres_texto, na.rm = T),
              `Tamanho justificativas (mediana)` = median(caracteres_justificativas, na.rm = T)) %>% 
    reactable()
```

### Alguns exemplos

```{r}
set.seed(13)

justificativas %>% 
    filter(justificada) %>% 
    select(siglaTipo, numero, ano, texto_inicial, justificativa) %>% 
    mutate(texto_inicial = paste0(str_sub(texto_inicial, 0, 250), '...'),
           justificativa = paste0(str_sub(justificativa, 0, 250), '...')) %>% 
    slice_sample(n = 5) %>% 
    reactable(striped = T,
              resizable = T)
```


### De quantas proposições conseguimos extrair as justificativas?

```{r}
justificativas %>% 
    count(justificada, ano) %>% 
    ggplot(aes(x = as.factor(ano),
               y = n,
               fill = justificada)) +
    geom_chicklet(width = .5,
                  position = "dodge") +
    scale_y_continuous(breaks = seq(0, 6e3, 1e3),
                       limits = c(0, 5500)) +
    labs(title = "Quantidade de proposições justificadas",
         subtitle = "Por ano",
         x = NULL,
         y = "nº proposições",
         fill = "Justificada")
```

```{r}
justificativas %>% 
    count(ano, justificada) %>% 
    pivot_wider(names_from = justificada,
                values_from = n) %>% 
    rename(justificada = `TRUE`,
           nao_justificada = `FALSE`) %>% 
    mutate(proporcao = round((justificada / (justificada + nao_justificada)) * 100, 1),
           sucesso = str_glue("{proporcao}%"),
           perda = str_glue("{round(100 - proporcao, 1)}%")) %>% 
    select(ano, extraimos = sucesso, perdemos = perda) %>% 
    reactable(strip = T)
```

```{r}
justificativas %>% 
    count(justificada, siglaTipo) %>% 
    ggplot(aes(x = reorder(siglaTipo, n),
               y = n,
               fill = justificada)) +
    geom_chicklet(width = .5,
                  position = "dodge") +
    scale_y_continuous(breaks = seq(0, 12e3, 3e3),
                       limits = c(0, 12e3)) +
    labs(title = "Quantidade de proposições justificadas",
         subtitle = "Por tipo",
         x = "Tipo",
         y = "nº proposições",
         fill = "Justificada")
```

```{r}
justificativas %>% 
    count(siglaTipo, justificada) %>% 
    pivot_wider(names_from = justificada,
                values_from = n,
                values_fill = 0) %>% 
    rename(justificada = `TRUE`,
           nao_justificada = `FALSE`) %>% 
    mutate(proporcao = round((justificada / (justificada + nao_justificada)) * 100, 1),
           sucesso = str_glue("{proporcao}%"),
           perda = str_glue("{round(100 - proporcao, 1)}%")) %>% 
    select(siglaTipo, extraimos = sucesso, perdemos = perda) %>% 
    reactable(strip = T)
```