---
title: "Matches nas falas em comissões"
output:
  html_document:
    theme: paper
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  # message = FALSE,
  # warning = FALSE,
  # fig.cap = '',
  # fig.align = 'center',
  fig.width = 8,
  fig.height = 5
)
Sys.setenv(LANGUAGE="pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
options(scipen = 999)
```

```{r warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(readr)
library(stringr)
library(here)
library(reactable)
library(lubridate)
```


```{r warning=FALSE, message=FALSE}
metadados_deputados = read_csv(
    "https://github.com/parlametria/dados-comportamentos/raw/main/data/ready/entidades/entidades.csv",
    col_types = cols(.default = col_character())
    ) %>%
    filter(casa == "camara", is_parlamentar == 1) %>%
    distinct(id = id_entidade, nome, uf, partido)
    
falas <- read_csv(here::here("data/ready/falas-comissoes.csv"))

deputados = metadados_deputados %>% 
    mutate(nome = toupper(nome)) %>% 
    group_by(id) %>% 
    filter(row_number()==n()) %>% 
    ungroup()
```

```{r}
mencionados = falas %>%
    filter(parlamentar) %>%
    distinct(nome, uf) %>%
    mutate(nome_original = nome,
    nome = str_replace_all(
        nome,
        c(
        "DR " = "DR. ",
        "PR " = "PR. ",
        "DRA " = "DRA. ",
        "MAJOR VITOR HUGO" = "VITOR HUGO",
        "JÚNIOR BOZZELLA" = "BOZZELLA", 
        "PROFESSOR LUIZÃO" = "LUIZÃO", 
        "JOÃO H CAMPOS" = "JOÃO H. CAMPOS"
        )
        ))
    
```


## Match a partir do nome. 

```{r echo=TRUE}
deputados_nome = mencionados %>% 
    inner_join(deputados,
               by = c("nome", "uf"), 
               suffix = c("_falas", "_parla")) %>% 
    distinct() %>% 
    rename(nome_parlametria = nome, id_camara = id)

matches <- deputados_nome %>% 
  summarise(matches = n()) %>% 
  pull(matches)
```

Utilizando o nome, `r matches` deputados foram recuperados.

```{r}
nao_encontrados = mencionados %>% 
    left_join(deputados,
              by = c("nome", "uf"), 
              suffix = c("_falas", "_parla")) %>% 
    distinct() %>% 
    filter(is.na(id)) %>% 
    select(-id)

nao_encontrados %>% 
    distinct(nome, uf) %>% 
    arrange(nome)
```

