---
title: "ETL para classificação"
output:
  html_document:
    theme: paper
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  # message = FALSE,
  # warning = FALSE,
  # fig.cap = '',
  # fig.align = 'center',
  fig.width = 6,
  fig.height = 5
)
Sys.setenv(LANGUAGE="pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
options(scipen = 999)
```

```{r setup warning=FALSE, message=FALSE}
library(tidyverse)
library(hrbrthemes)
library(here)
theme_set(theme_ipsum_rc())
```

```{r}
justificativas = read_csv(here::here("data/ready/justificativas_19-21.csv"),
                          col_types = c("cciTiccccTcccll")) %>% 
  janitor::clean_names()

todas_ma = read_csv("https://github.com/parlametria/relatorio-bianuario-ma/raw/main/data/inputs/2-fetch-input/proposicoes/proposicoes_preenchidas.csv")

avaliacoes = read_csv("https://github.com/parlametria/relatorio-bianuario-ma/raw/main/data/ready/proposicoes.csv")
```

```{r}
dataset = todas_ma %>%
    filter(casa == "camara", !is.na(classificacao_ambientalismo), 
           !(sigla_tipo %in% c("MPV", "PDL")),
           ano %in% c(2019, 2020)) %>%
    select(
        id,
        sigla_tipo,
        numero,
        ano,
        classificacao_ambientalismo,
        ementa,
        autor,
        link
    ) %>% 
    mutate(relacionada = if_else(
        classificacao_ambientalismo == "Fora do tema",
        0,
        1
    ), 
    id = as.character(id))

cj = dataset %>%  ## TO DO: PQ HÁ PROPS APENAS EM X?
  left_join(select(justificativas, -ementa)) %>% 
  filter(!is.na(data_apresentacao))

extras = select(justificativas, -ementa) %>% 
  anti_join(dataset) %>% 
  mutate(relacionada = 0)

count(cj, relacionada)

final = bind_rows(cj, extras) %>% 
  filter(!is.na(justificada), justificada)  

final_peq = cj %>% 
  filter(!is.na(justificada), justificada)  

final %>% 
  count(relacionada, justificada)

final_peq %>% 
  count(relacionada)
```

```{r}
final_peq %>% 
  filter(!is.na(texto_completo)) %>% 
  write_csv("gabarito.csv")

final %>% 
  filter(!is.na(texto_completo)) %>% 
  write_csv("gabarito-tudo.csv")
```

